os: osx
language: python
sudo: required
services:
  - docker
env:
  global:
    - CONAN_UPLOAD: 1
    - CONAN_REFERENCE: "node/6.1.0"
    - CONAN_USERNAME: "silkedit"
    - CONAN_CHANNEL: "ci"
    - CONAN_TOTAL_PAGES: 1
  matrix:
    - CONAN_GCC_VERSIONS: 4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS: 4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS: 5.2 CONAN_USE_DOCKER=1

matrix:
   include:
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env: CONAN_CURRENT_PAGE=1

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
